/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza_package;
/**
 *
 * @author nikol
 */
public class New_pizza_form extends javax.swing.JFrame {
    
    
    private Order o;
    private Home_form hf;
    /**
     * Creates new form New_pizza_form
     */
    public New_pizza_form() {
        initComponents();
    }
    
    public New_pizza_form(Home_form hf) {
        initComponents();
        this.hf = hf;
    }
    
    public void pizzaInfo(){
        Pizza pizza = cookPizza();
        TextBox.setText(pizza.Info());
    }
    

    
    public Pizza cookPizza(){
        Size newSize = (Size)SizeList.getSelectedItem(); 
        Crust newCrust = (Crust)CrustList.getSelectedItem();
        Topping1 newTopping1 = (Topping1)Topping1List.getSelectedItem();
        Topping2 newTopping2 = (Topping2)Topping2List.getSelectedItem();
        Sauce newSauce = (Sauce)SauceList.getSelectedItem();
        return new Pizza(newSize, newCrust, newSauce, newTopping1, newTopping2);
        
    }
    
    public void addPizza(Pizza p) {
        hf.setOrder(p); 
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jColorChooser1 = new javax.swing.JColorChooser();
        SizeLabel = new javax.swing.JLabel();
        SizeList = new javax.swing.JComboBox(Size.values());
        CrustList = new javax.swing.JComboBox(Crust.values());
        ;
        Topping1List = new javax.swing.JComboBox(Topping1.values());
        Topping2List = new javax.swing.JComboBox(Topping2.values());
        SauceList = new javax.swing.JComboBox(Sauce.values());
        jScrollPane1 = new javax.swing.JScrollPane();
        TextBox = new javax.swing.JTextArea();
        Cancel = new javax.swing.JButton();
        AddToOrder = new javax.swing.JButton();
        CrustLabel = new javax.swing.JLabel();
        Topping1Label = new javax.swing.JLabel();
        Topping2Label = new javax.swing.JLabel();
        SauceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NEW PIZZA FORM");

        SizeLabel.setText("SIZE");

        SizeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeListActionPerformed(evt);
            }
        });

        CrustList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrustListActionPerformed(evt);
            }
        });

        Topping1List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Topping1ListActionPerformed(evt);
            }
        });

        Topping2List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Topping2ListActionPerformed(evt);
            }
        });

        SauceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SauceListActionPerformed(evt);
            }
        });

        TextBox.setEditable(false);
        TextBox.setColumns(20);
        TextBox.setRows(5);
        jScrollPane1.setViewportView(TextBox);

        Cancel.setText("CANCEL");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        AddToOrder.setText("ADD TO ORDER");
        AddToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToOrderActionPerformed(evt);
            }
        });

        CrustLabel.setText("CRUST");

        Topping1Label.setText("TOPPING 1");

        Topping2Label.setText("TOPPING 2");

        SauceLabel.setText("SAUCE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SizeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SizeList, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CrustLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Topping1Label, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CrustList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Topping1List, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Topping2Label)
                                .addGap(18, 18, 18)
                                .addComponent(Topping2List, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SauceLabel)
                                .addGap(18, 18, 18)
                                .addComponent(SauceList, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddToOrder)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SizeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SizeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrustList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrustLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Topping1List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Topping1Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Topping2List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Topping2Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SauceList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SauceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(AddToOrder))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SizeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeListActionPerformed
        pizzaInfo();
         
    }//GEN-LAST:event_SizeListActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
        //Home_form f = new Home_form();
        hf.setVisible(true);
    }//GEN-LAST:event_CancelActionPerformed

    private void CrustListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrustListActionPerformed
        pizzaInfo();
 
    }//GEN-LAST:event_CrustListActionPerformed

    private void Topping1ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Topping1ListActionPerformed
        pizzaInfo();
   
    }//GEN-LAST:event_Topping1ListActionPerformed

    private void Topping2ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Topping2ListActionPerformed
        pizzaInfo();
   
    }//GEN-LAST:event_Topping2ListActionPerformed

    private void SauceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SauceListActionPerformed
       pizzaInfo();
    
    }//GEN-LAST:event_SauceListActionPerformed

    private void AddToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToOrderActionPerformed
        Pizza p = cookPizza();
        this.addPizza(p);
        String info = p.Info();
        this.TextBox.setText(info);
        dispose();
        hf.setVisible(true);
    }//GEN-LAST:event_AddToOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_pizza_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_pizza_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_pizza_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_pizza_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_pizza_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToOrder;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel CrustLabel;
    private javax.swing.JComboBox<Crust> CrustList;
    private javax.swing.JLabel SauceLabel;
    private javax.swing.JComboBox<Sauce> SauceList;
    private javax.swing.JLabel SizeLabel;
    private javax.swing.JComboBox<Size> SizeList;
    private javax.swing.JTextArea TextBox;
    private javax.swing.JLabel Topping1Label;
    private javax.swing.JComboBox<Topping1> Topping1List;
    private javax.swing.JLabel Topping2Label;
    private javax.swing.JComboBox<Topping2> Topping2List;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
